name: Ant

on:
#  schedule:
#    - cron: "0 18 * * 1-5"
#  push:
#    branches:
#      - master
#    tags:
#      - 'v*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Run unit test'

jobs:
  ant-build-backend:
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Install base dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y autoconf automake gcc make wget unzip gettext sass default-jdk libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libssh2-1-dev libopenipmi-dev unixodbc-dev libldap2-dev libgnutls-dev
        sudo apt-get install -y ant ant-contrib phpunit cppcheck clang lcov libcmocka libcmocka-dev libyaml-dev
    - name: Install database dependencies
      run: sudo apt-get install -y libmysqlclient-dev libpq-dev
    - name: Run build backend
      run: |
        ant -f build-backend.xml
        ant -f build-backend.xml cmocka-tests
        ant -f build-backend.xml cmocka-ora-tests
        ant -f build-backend.xml cppcheck-static-analyzer
