name: Ant

on:
#  schedule:
#    - cron: "0 18 * * 1-5"
#  push:
#    branches:
#      - master
#    tags:
#      - 'v*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Run unit test'

jobs:
  ubuntu-job:
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Install base dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y autoconf automake gcc make wget unzip gettext sass default-jdk libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libssh2-1-dev libopenipmi-dev unixodbc-dev libldap2-dev libgnutls28-dev libpcre3-dev libssh-dev
        sudo apt-get install -y ant ant-contrib phpunit cppcheck golang clang clang-tools lcov libcmocka-dev libyaml-dev
    - name: Installing Golang
      run: |
        sudo curl -O https://dl.google.com/go/go1.15.1.linux-amd64.tar.gz
        sudo tar -xf go1.15.1.linux-amd64.tar.gz -C /usr/local
        sudo chown -R root:root /usr/local/go
        echo '::set-env name=GOPATH::${{ runner.workspace }}/go'
        echo '::add-path::${{ runner.workspace }}/go/bin'
        echo '::add-path::/usr/local/go/bin'
    - name: Install database dependencies
      run: sudo apt-get install -y libmysqlclient-dev libpq-dev
    - name: Run backend build tests with MySQL...
      run: ant -DDBTYPE=MYSQL -f build-backend.xml
    - name: Run backend build tests with PostgreSQL...
      run: ant -DDBTYPE=POSTGRESQL -f build-backend.xml
#    - name: Run backend build tests with Oracle...
#      run: ant -DDBTYPE=ORACLE -f build-backend.xml
    - name: Run backend test cppcheck-static-analyzer...
      run: ant -f build-backend.xml cppcheck-static-analyzer
    - name: Run backend test clang-static-analyzer...
      run: ant -f build-backend.xml clang-static-analyzer
    - name: Run backend test cmocka-tests...
      run: ant -f build-backend.xml cmocka-tests
#    - name: Run backend test cmocka-ora-tests...
#      run: ant -f build-backend.xml cmocka-ora-tests
