name: Linux

on:
#  schedule:
#    - cron: "0 18 * * 1-5"
#  push:
#    branches:
#      - master
#    tags:
#      - 'v*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Update all binary'

jobs:
  github-job-mysql:
    name: Ubuntu (MySQL)
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Install base dependencies
      run: sudo apt-get install -y autoconf automake gcc make wget unzip gettext default-jdk libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libssh2-1-dev libopenipmi-dev unixodbc-dev libldap2-dev
    - name: Install database dependencies
      run: sudo apt-get install -y libmysqlclient-dev
    - name: Set exec bit
      run: chmod a+x ./bootstrap.sh && chmod a+x ./create/bin/*.{sh,pl}
    - name: Run bootstrap
      run: ./bootstrap.sh
    - name: Run configure
      run: ./configure --with-libpthread --with-libpcre --with-libcurl --with-libxml2 --with-net-snmp --with-openssl --enable-ipv6 --with-ssh2 --with-openipmi --with-unixodbc --with-ldap --enable-server --enable-proxy --enable-agent --enable-java --sysconfdir=/etc/zabbix --with-mysql
    - name: Run make
      run: make
    - name: Run make dbschema
      run: make dbschema
    - name: Run make gettext
      run: make gettext
    - name: Run make dist
      run: make dist
    - uses: actions/upload-artifact@v2
      with:
        name: zabbix_server ubuntu-18.04 mysql
        path: src/zabbix_server/zabbix_server
  github-job-pgsql:
    name: Ubuntu (PgSQL)
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Install base dependencies
      run: sudo apt-get install -y autoconf automake gcc make wget unzip gettext default-jdk libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libssh2-1-dev libopenipmi-dev unixodbc-dev libldap2-dev
    - name: Install database dependencies
      run: sudo apt-get install -y libpq-dev
    - name: Run bootstrap
      run: ./bootstrap.sh
    - name: Run configure
      run: ./configure --with-libpthread --with-libpcre --with-libcurl --with-libxml2 --with-net-snmp --with-openssl --enable-ipv6 --with-ssh2 --with-openipmi --with-unixodbc --with-ldap --enable-server --enable-proxy --enable-agent --enable-java --sysconfdir=/etc/zabbix --with-postgresql
    - name: Run make
      run: make
    - name: Run make dbschema
      run: make dbschema
    - name: Run make gettext
      run: make gettext
    - name: Run make dist
      run: make dist
    - uses: actions/upload-artifact@v2
      with:
        name: zabbix_server ubuntu-18.04 pgsql
        path: src/zabbix_server/zabbix_server
