name: ReleaseCandidate

on:
#  push:
#    branches:
#      - master
#    tags:
#      - 'v*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Create new release candidate'

jobs:
  github-job-release:
    name: Ubuntu
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Update packages
      run: sudo apt-get update --fix-missing -y
    - name: Upgrade packages
      run: sudo apt-get upgrade -y
    - name: Install base dependencies
      run: sudo apt-get install -y autoconf automake gcc make wget unzip gettext sass default-jdk libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libssh2-1-dev libopenipmi-dev unixodbc-dev libldap2-dev libconfig-dev
    - name: Install database dependencies
      run: sudo apt-get install -y libmysqlclient-dev
    - name: Run bootstrap
      run: ./bootstrap.sh
    - name: Run configure
      run: ./configure
    - name: Build dbschema
      run: make dbschema
    - name: Build gettext
      run: make gettext
    - name: Build css
      run: make css
    - name: Build dist
      run: make dist
    - name: Get current Zabbix version
      run: echo "::set-env name=ZABBIX_VERSION::$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')"
    - name: Get short SHA
      run: echo ::set-env name=GITHUB_SHA_SHORT::$(echo $GITHUB_SHA | cut -c 1-6)
    - name: Delete old drafts releases
      uses: hugo19941994/delete-draft-releases@v0.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create new draft release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "latest"
        release_name: Zabbix v${{ env.ZABBIX_VERSION }} (${{ env.GITHUB_SHA_SHORT }}) (unofficial) release candidate
        draft: true
        prerelease: false
    - name: Upload draft release asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
        asset_name: zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
        asset_content_type: application/gzip
