name: TestBuild

on:
#  schedule:
#    - cron: "0 18 * * 1-5"
#  push:
#    branches:
#      - master
#    tags:
#      - 'v*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Run test build'

jobs:
  github-job-mysql:
    name: Ubuntu (MySQL)
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Update packages
      run: sudo apt-get update --fix-missing -y
    - name: Upgrade packages
      run: sudo apt-get upgrade -y
    - name: Install base dependencies
      run: sudo apt-get install -y autoconf automake gcc make wget unzip gettext sass default-jdk libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libssh2-1-dev libopenipmi-dev unixodbc-dev libldap2-dev
    - name: Install database dependencies
      run: sudo apt-get install -y libmysqlclient-dev
    - name: Run bootstrap
      run: ./bootstrap.sh
    - name: Run configure
      run: ./configure
    - name: Run make
      run: make
    - name: Run make dbschema
      run: make dbschema
    - name: Run make gettext
      run: make gettext
    - name: Run make css
      run: make css
    - name: Run make dist
      run: make dist
    - name: Get current Zabbix version
      run: echo "::set-env name=ZABBIX_VERSION::$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')"
    - name: Get short SHA
      run: echo ::set-env name=GITHUB_SHA_SHORT::$(echo $GITHUB_SHA | cut -c 1-6)
    - name: Extract distr
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Change directory
      run: cd zabbix-${{ env.ZABBIX_VERSION }}/
    - name: Run configure
      run: ./configure --with-libpthread --with-libpcre --with-libcurl --with-libxml2 --with-net-snmp --with-openssl --enable-ipv6 --with-ssh2 --with-openipmi --with-unixodbc --with-ldap --enable-server --enable-proxy --enable-agent --enable-java --sysconfdir=/etc/zabbix --with-mysql
    - name: Build
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: zabbix_server v${{ env.ZABBIX_VERSION }} (${{ env.GITHUB_SHA_SHORT }} ubuntu-18.04 mysql)
        path: src/zabbix_server/zabbix_server
  github-job-pgsql:
    name: Ubuntu (PgSQL)
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Update packages
      run: sudo apt-get update --fix-missing -y
    - name: Upgrade packages
      run: sudo apt-get upgrade -y
    - name: Install base dependencies
      run: sudo apt-get install -y autoconf automake gcc make wget unzip gettext sass default-jdk libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libssh2-1-dev libopenipmi-dev unixodbc-dev libldap2-dev
    - name: Install database dependencies
      run: sudo apt-get install -y libpq-dev
    - name: Run bootstrap
      run: ./bootstrap.sh
    - name: Run configure
      run: ./configure
    - name: Run make
      run: make
    - name: Run make dbschema
      run: make dbschema
    - name: Run make gettext
      run: make gettext
    - name: Run make css
      run: make css
    - name: Run make dist
      run: make dist
    - name: Get current Zabbix version
      run: echo "::set-env name=ZABBIX_VERSION::$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')"
    - name: Get short SHA
      run: echo ::set-env name=GITHUB_SHA_SHORT::$(echo $GITHUB_SHA | cut -c 1-6)
    - name: Extract distr
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Change directory
      run: cd zabbix-${{ env.ZABBIX_VERSION }}/
    - name: Run configure
      run: ./configure --with-libpthread --with-libpcre --with-libcurl --with-libxml2 --with-net-snmp --with-openssl --enable-ipv6 --with-ssh2 --with-openipmi --with-unixodbc --with-ldap --enable-server --enable-proxy --enable-agent --enable-java --sysconfdir=/etc/zabbix --with-postgresql
    - name: Build
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: zabbix_server v${{ env.ZABBIX_VERSION }} (${{ env.GITHUB_SHA_SHORT }} ubuntu-18.04 pgsql)
        path: src/zabbix_server/zabbix_server
