name: TestBuild

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "bin/**"
      - "build/**"
      - "conf/**"
      - "create/**"
      - "database/**"
      - "man/**"
      - "misc/**"
      - "packages/**"
      - "sass/**"
      - "templates/**"
      - "tests/**"
      - "frontends/**"
#  schedule:
#    - cron: "0 18 * * 1-5"
#  push:
#    branches:
#      - master
#    tags:
#      - 'v*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Run test build'

jobs:
  github-job-ubuntu-bionic-mysql:
    name: Ubuntu 18.04 (MySQL)
    runs-on: [ubuntu-18.04]
    steps:
    - name: Installing Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.1
      id: go
    - name: Install dependencies
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y autoconf automake gcc make wget unzip gettext default-jdk libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libpcre3-dev libssh2-1-dev libopenipmi-dev unixodbc-dev libldap2-dev
        sudo apt-get install -y libmysqlclient-dev
        sudo wget https://github.com/sass/dart-sass/releases/download/1.49.7/dart-sass-1.49.7-linux-x64.tar.gz -O /tmp/dart-sass-linux-x64.tar.gz
        sudo tar -zxf /tmp/dart-sass-linux-x64.tar.gz -C /tmp && yes | sudo cp /tmp/dart-sass/sass /usr/local/sbin && sudo rm -rf /tmp/dart-sass dart-sass-linux-x64.tar.gz
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Build zabbix dist
      run: |
         ./bootstrap.sh
         ./configure
         make dbschema
         make gettext
         make css
         make dist
         echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
         echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - name: Prepare build
      run: |
        tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Build
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        ./configure --with-libpthread --with-libpcre --with-libcurl --with-libxml2 --with-net-snmp --with-openssl --enable-ipv6 --with-ssh2 --with-openipmi --with-unixodbc --with-ldap --enable-server --enable-proxy --enable-agent --enable-agent2 --enable-java --sysconfdir=/etc/zabbix --with-mysql
        make
        ./src/zabbix_server/zabbix_server -V
        ./src/zabbix_proxy/zabbix_proxy -V
        ./src/zabbix_agent/zabbix_agentd -V
  github-job-ubuntu-bionic-pgsql:
    name: Ubuntu 18.04 (PgSQL)
    runs-on: [ubuntu-18.04]
    steps:
    - name: Installing Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.1
      id: go
    - name: Install dependencies
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y autoconf automake gcc make wget unzip gettext default-jdk libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libssh2-1-dev libopenipmi-dev unixodbc-dev libldap2-dev
        sudo apt-get install -y libpq-dev
        sudo wget https://github.com/sass/dart-sass/releases/download/1.49.7/dart-sass-1.49.7-linux-x64.tar.gz -O /tmp/dart-sass-linux-x64.tar.gz
        sudo tar -zxf /tmp/dart-sass-linux-x64.tar.gz -C /tmp && yes | sudo cp /tmp/dart-sass/sass /usr/local/sbin && sudo rm -rf /tmp/dart-sass dart-sass-linux-x64.tar.gz
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Build zabbix dist
      run: |
         ./bootstrap.sh
         ./configure
         make dbschema
         make gettext
         make css
         make dist
         echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
         echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - name: Prepare build
      run: |
        tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Build
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        ./configure --with-libpthread --with-libpcre --with-libcurl --with-libxml2 --with-net-snmp --with-openssl --enable-ipv6 --with-ssh2 --with-openipmi --with-unixodbc --with-ldap --enable-server --enable-proxy --enable-agent --enable-agent2 --enable-java --sysconfdir=/etc/zabbix --with-postgresql
        make
        ./src/zabbix_server/zabbix_server -V
        ./src/zabbix_proxy/zabbix_proxy -V
        ./src/zabbix_agent/zabbix_agentd -V
  github-job-ubuntu-focal-mysql:
    name: Ubuntu 20.04 (MySQL)
    runs-on: [ubuntu-20.04]
    steps:
    - name: Installing Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.1
      id: go
    - name: Install dependencies
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y autoconf automake gcc make wget unzip gettext default-jdk libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libpcre3-dev libssh2-1-dev libopenipmi-dev unixodbc-dev libldap2-dev
        sudo apt-get install -y libmysqlclient-dev
        sudo wget https://github.com/sass/dart-sass/releases/download/1.54.5/dart-sass-1.54.5-linux-x64.tar.gz -O /tmp/dart-sass-linux-x64.tar.gz
        sudo tar -zxf /tmp/dart-sass-linux-x64.tar.gz -C /tmp && yes | sudo cp /tmp/dart-sass/sass /usr/local/sbin && sudo rm -rf /tmp/dart-sass dart-sass-linux-x64.tar.gz
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Build zabbix dist
      run: |
         ./bootstrap.sh
         ./configure
         make dbschema
         make gettext
         make css
         make dist
         echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
         echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - name: Prepare build
      run: |
        tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Build
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        ./configure --with-libpthread --with-libpcre --with-libcurl --with-libxml2 --with-net-snmp --with-openssl --enable-ipv6 --with-ssh2 --with-openipmi --with-unixodbc --with-ldap --enable-server --enable-proxy --enable-agent --enable-agent2 --enable-java --sysconfdir=/etc/zabbix --with-mysql
        make
        ./src/zabbix_server/zabbix_server -V
        ./src/zabbix_proxy/zabbix_proxy -V
        ./src/zabbix_agent/zabbix_agentd -V
  github-job-ubuntu-focal-pgsql:
    name: Ubuntu 20.04 (PgSQL)
    runs-on: [ubuntu-20.04]
    steps:
    - name: Installing Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.1
      id: go
    - name: Install dependencies
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y autoconf automake gcc make wget unzip gettext default-jdk libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libssh2-1-dev libopenipmi-dev unixodbc-dev libldap2-dev
        sudo apt-get install -y libpq-dev
        sudo wget https://github.com/sass/dart-sass/releases/download/1.54.5/dart-sass-1.54.5-linux-x64.tar.gz -O /tmp/dart-sass-linux-x64.tar.gz
        sudo tar -zxf /tmp/dart-sass-linux-x64.tar.gz -C /tmp && yes | sudo cp /tmp/dart-sass/sass /usr/local/sbin && sudo rm -rf /tmp/dart-sass dart-sass-linux-x64.tar.gz
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Build zabbix dist
      run: |
         ./bootstrap.sh
         ./configure
         make dbschema
         make gettext
         make css
         make dist
         echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
         echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - name: Prepare build
      run: |
        tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Build
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        ./configure --with-libpthread --with-libpcre --with-libcurl --with-libxml2 --with-net-snmp --with-openssl --enable-ipv6 --with-ssh2 --with-openipmi --with-unixodbc --with-ldap --enable-server --enable-proxy --enable-agent --enable-agent2 --enable-java --sysconfdir=/etc/zabbix --with-postgresql
        make
        ./src/zabbix_server/zabbix_server -V
        ./src/zabbix_proxy/zabbix_proxy -V
        ./src/zabbix_agent/zabbix_agentd -V