name: TestBuild

on:
#  schedule:
#    - cron: "0 18 * * 1-5"
#  push:
#    branches:
#      - master
#    tags:
#      - 'v*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Run test build'

jobs:
  github-job-mysql:
    name: Ubuntu (MySQL)
    runs-on: [ubuntu-18.04]
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake gcc make wget unzip gettext sass default-jdk libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libssh2-1-dev libopenipmi-dev unixodbc-dev libldap2-dev
        sudo apt-get install -y libmysqlclient-dev
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Build zabbix dist
      run: |
        ./bootstrap.sh
        ./configure
         make dist
         echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
         echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - name: Prepare build
      run: |
        tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Build
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        ./configure --with-libpthread --with-libpcre --with-libcurl --with-libxml2 --with-net-snmp --with-openssl --enable-ipv6 --with-ssh2 --with-openipmi --with-unixodbc --with-ldap --enable-server --enable-proxy --enable-agent --enable-java --sysconfdir=/etc/zabbix --with-mysql
        make
  github-job-pgsql:
    name: Ubuntu (PgSQL)
    runs-on: [ubuntu-18.04]
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y autoconf automake gcc make wget unzip gettext sass default-jdk libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libssh2-1-dev libopenipmi-dev unixodbc-dev libldap2-dev
        sudo apt-get install -y libpq-dev
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Build zabbix dist
      run: |
        ./bootstrap.sh
        ./configure
         make dist
         echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
         echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - name: Prepare build
      run: |
        tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Build
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        ./configure --with-libpthread --with-libpcre --with-libcurl --with-libxml2 --with-net-snmp --with-openssl --enable-ipv6 --with-ssh2 --with-openipmi --with-unixodbc --with-ldap --enable-server --enable-proxy --enable-agent --enable-java --sysconfdir=/etc/zabbix --with-postgresql
        make
