name: CreateUbuntuDEB

on:
#  push:
#    branches:
#      - master
#    paths-ignore:
#      - ".github/**"
#      - "bin/**"
#      - "build/**"
#      - "conf/**"
#      - "create/**"
#      - "database/**"
#      - "man/**"
#      - "misc/**"
#      - "packages/**"
#      - "sass/**"
#      - "templates/**"
#      - "tests/**"
#      - "frontends/**"
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Create Ubuntu packages'

jobs:
  github-job:
    name: Ubuntu (Bionic)
    runs-on: [ubuntu-18.04]
    steps:
    - name: Installing Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
      id: go
    - name: Install Golang dependencies
      env:
        GO111MODULE: on
      run: |
        go get -u golang.org/x/lint/golint
        go get -u github.com/kisielk/errcheck
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
    - name: Install base dependencies
      run: |
        sudo apt-get install -y autoconf automake gcc make wget unzip gettext sass libsnmp-dev libcurl4-openssl-dev libldap2-dev libiksemel-dev libopenipmi-dev libssh2-1-dev unixodbc-dev openjdk-8-jdk libxml2-dev libpcre3-dev libevent-dev libssl-dev
        sudo apt-get install -y dpkg-dev devscripts git dh-make build-essential autoconf autotools-dev quilt pkg-config tar xz-utils curl
        sudo apt-get install -y libmysqlclient-dev libpq-dev libsqlite3-dev
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Run bootstrap
      run: ./bootstrap.sh
    - name: Run configure
      run: ./configure
    - name: Build dbschema
      run: make dbschema
    - name: Build gettext
      run: make gettext
    - name: Build css
      run: make css
    - name: Build dist
      run: make dist
    - name: Set variables
      run: |
        echo "ZABBIX_ORIG_VERSION=4.4.10" >> $GITHUB_ENV
        echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
        echo "ZABBIX_VERSION_SHORT=$(echo ${{ env.ZABBIX_VERSION }} | awk -F. '{print $1"."$2}')" >> $GITHUB_ENV
    - name: Extract distr
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz && cd zabbix-${{ env.ZABBIX_VERSION }}
    - name: Download original sources
      run: wget "https://repo.zabbix.com/zabbix/${{ env.ZABBIX_VERSION_SHORT }}/$(lsb_release -i -s | tr '[:upper:]' '[:lower:]')/pool/main/z/zabbix/zabbix_${{ env.ZABBIX_ORIG_VERSION }}-1+$(lsb_release -c -s).debian.tar.xz" -O debian.tar.xz && tar -xvf debian.tar.xz
    - name: Prepare build DEB
      run: dch -v "1:${{ env.ZABBIX_VERSION }}-1+$(lsb_release -c -s)" --distribution "$(lsb_release -c -s)" "Release ${{ env.ZABBIX_VERSION }}"
    - name: Build DEB
      env:
        GO111MODULE: on
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
        dpkg-buildpackage -b
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.REPO_SERVER_PRIVATE_KEY }}
        known_hosts: ${{ secrets.REPO_SERVER_KNOWN_HOSTS }}
    - name: Upload deb from dev server
      run: scp ../*.deb ${{ secrets.REPO_SERVER_USER }}@${{ secrets.REPO_SERVER }}:pkgs/$(lsb_release -i -s | tr '[:upper:]' '[:lower:]')/pool/main/$(lsb_release -c -s)/
